import Head from 'next/head'
// import React, { Children } from 'react'
import Header from './Header'
import LeflAside from './LeflAside'
import RightAside from './RightAside'
import Footer from './Footer'

export default function CommanLayout({children}) {
    return (
        <>
            <Head>
                <title>11.0.0 Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="container-fluid">
                <Header />

                <main className="row m-0">
                    <LeflAside />

                    {children}
                    
                    <RightAside />
                </main>

                <Footer />
            </div>
      
        </>
    )
}
